const LIMIAR=50,SIGMA=2.4;
function needOnScreen(w,remain,target){if(w<=0.0001)return remain>=target?0:101;if(w>=0.999)return target;return(target-(1-w)*remain)/w;}
function firstRoundAt(pct){const saved=snapshotPcts();applyTypicalOrder(pct);const exp=expectedNow();const rest=pollsRemaining();const w=clamp(pct,0,100)/100;restorePcts(saved);return{w,exp,rest,needL:needOnScreen(w,rest.l,LIMIAR),needF:needOnScreen(w,rest.f,LIMIAR),needLEasy:needOnScreen(w,rest.l+SIGMA,LIMIAR),needLHard:needOnScreen(w,rest.l-SIGMA,LIMIAR),needFEasy:needOnScreen(w,rest.f+SIGMA,LIMIAR),needFHard:needOnScreen(w,rest.f-SIGMA,LIMIAR),finalL:w*exp.l+(1-w)*rest.l,finalF:w*exp.f+(1-w)*rest.f};}
function fmtNeed(n){if(!Number.isFinite(n))return '—';if(n>100)return 'impossível';if(n<=0)return 'já garantido';return fmt(n)+'%';}
function trackStatus(expected,need){if(need>100)return{cls:'bad',txt:'Com o que falta, as pesquisas não dão 50% + 1'};if(need<=0)return{cls:'ok',txt:'O que falta já bastaria para passar de 50%'};if(expected>=need+2)return{cls:'ok',txt:'Neste ritmo de pesquisa, segue na rota do 1º turno'};if(expected>=need)return{cls:'warn',txt:'No limite da rota para o 1º turno'};return{cls:'bad',txt:'Abaixo da rota: as pesquisas deste pedaço não sustentam 50% + 1'};}
function fillCand(prefix,expected,need,easy,hard,rest,finalP){document.getElementById(prefix+'Exp').textContent=fmt(expected)+'%';document.getElementById(prefix+'Need').textContent=fmtNeed(need);document.getElementById(prefix+'Band').textContent=(easy>100&&hard>100)?'mesmo no cenário otimista das pesquisas, não fecha':'faixa das pesquisas no que falta: '+fmt(rest-SIGMA)+'% a '+fmt(rest+SIGMA)+'% · na tela precisaria entre '+fmtNeed(hard)+' e '+fmtNeed(easy);document.getElementById(prefix+'Final').textContent=fmt(finalP)+'%';const st=trackStatus(expected,need);const el=document.getElementById(prefix+'St');el.className='chip '+st.cls;el.textContent=st.cls==='ok'?'na rota':st.cls==='warn'?'no limite':'fora da rota';document.getElementById(prefix+'StTxt').textContent=st.txt;}
function drawNeedChart(pct){const svg=document.getElementById('chart1t');if(!svg)return;const W=640,H=260,L=38,R=14,T=18,B=30,iw=W-L-R,ih=H-T-B;const x=p=>L+iw*p/100;const y=v=>T+ih*(1-(clamp(v,10,80)-10)/70);const saved=snapshotPcts();const pts=[];for(let p=2;p<=100;p+=2){applyTypicalOrder(p);const exp=expectedNow();const rest=pollsRemaining();const w=p/100;pts.push({p,eL:exp.l,eF:exp.f,nL:needOnScreen(w,rest.l,LIMIAR),nF:needOnScreen(w,rest.f,LIMIAR)});}restorePcts(saved);const path=(key,color,dash)=>{let d='',started=false;pts.forEach(pt=>{const v=pt[key];if(!Number.isFinite(v)||v<0||v>100){started=false;return;}d+=(started?'L':'M')+x(pt.p).toFixed(1)+','+y(v).toFixed(1)+' ';started=true;});return `<path d="${d}" fill="none" stroke="${color}" stroke-width="${dash?1.6:2}" ${dash?'stroke-dasharray="5 4"':''} opacity="${dash?0.9:0.55}"/>`;};const grid=[20,30,40,50,60,70].map(v=>`<line class="gridline" x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}"/><text x="4" y="${y(v)+3}">${v}</text>`).join('');const axis=[0,25,50,75,100].map(p=>`<text x="${x(p)}" y="${H-8}" text-anchor="middle">${p}%</text>`).join('');svg.innerHTML=`${grid}${axis}<line x1="${L}" x2="${W-R}" y1="${y(50)}" y2="${y(50)}" stroke="#1c1917" stroke-width="1" opacity=".35"/><text x="${W-R}" y="${y(50)-5}" text-anchor="end">50% + 1</text>${path('eL','var(--lula)')}${path('eF','var(--flavio)')}${path('nL','var(--lula)',true)}${path('nF','var(--flavio)',true)}<line x1="${x(pct)}" x2="${x(pct)}" y1="${T}" y2="${H-B}" stroke="#c4bbb0" stroke-dasharray="2 3"/><text x="${L}" y="12">sólido = previsto na TV</text><text x="${L+148}" y="12">tracejado = mínimo para fechar no 1º turno</text>`;}
function updateFirstRound(){const pct=clamp(parseFloat(document.getElementById('pctBR').value)||0,0,100);const slider=document.getElementById('slider1t');if(slider&&Math.abs(parseFloat(slider.value)-pct)>0.05)slider.value=pct;document.getElementById('slider1tVal').textContent=fmt(pct)+'% do Brasil apurado';const r=firstRoundAt(pct);fillCand('l1t',r.exp.l,r.needL,r.needLEasy,r.needLHard,r.rest.l,r.finalL);fillCand('f1t',r.exp.f,r.needF,r.needFEasy,r.needFHard,r.rest.f,r.finalF);const who=r.finalL>=LIMIAR&&r.finalL>r.finalF?'As pesquisas deste caminho apontam Lula acima de 50% no fim.':r.finalF>=LIMIAR&&r.finalF>r.finalL?'As pesquisas deste caminho apontam Flávio acima de 50% no fim.':'Com as pesquisas de hoje, o caminho aponta segundo turno: ninguém chega a 50% + 1 dos válidos.';document.getElementById('t1tSum').textContent=who+` Palpite se a TV andasse exatamente como as pesquisas: Lula ${fmt(r.finalL)}% × Flávio ${fmt(r.finalF)}%.`;drawNeedChart(pct);}
function bindFirstRound(){const sl=document.getElementById('slider1t');if(!sl)return;sl.addEventListener('input',()=>{document.getElementById('pctBR').value=sl.value;document.getElementById('pctBR').dispatchEvent(new Event('input'));updateFirstRound();});document.getElementById('pctBR').addEventListener('input',updateFirstRound);document.getElementById('modeTabs').addEventListener('click',()=>setTimeout(updateFirstRound,0));updateFirstRound();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindFirstRound);else bindFirstRound();
